#server configuration
server:
  port: ${PORT}
    #error:
  #include-stacktrace: never

#spring configuration
spring:
  application:
    name: DemoKT


  #datasource
  datasource:
    url: ${DB_URL_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none # Opciones: create, create-drop, update, validate, none

#Open api swagger ui
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    persist-authorization: true
    tags-sorter: alpha
    doc-expansion: list  # none | list | full


swg:
  server:
    url: ${SERVER_URL}
    description: ${SERVER_DESCRIPTION}
